"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5zhe3pt6qw_x=t-u)-r=@co0y8$6!p4+5#8h5*r)cx4#mw3=oj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app1'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'/'pages'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jr_technologies',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',  # Default MySQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR/'static',
    BASE_DIR/'static'/'css',
    BASE_DIR/'static'/'css'/'patterns',
    BASE_DIR/'static'/'css'/'plugins',
    BASE_DIR/'static'/'css'/'plugins'/'blueimp'/'css',
    BASE_DIR/'static'/'css'/'plugins'/'blueimp'/'img',
    BASE_DIR/'static'/'css'/'plugins'/'bootstrap-rtl',
    BASE_DIR/'static'/'css'/'plugins'/'chosen',
    BASE_DIR/'static'/'css'/'plugins'/'codemirror',
    BASE_DIR/'static'/'css'/'plugins'/'colorpicker',
    BASE_DIR/'static'/'css'/'plugins'/'cropper',
    BASE_DIR/'static'/'css'/'plugins'/'datapicker',
    BASE_DIR/'static'/'css'/'plugins'/'dataTables',
    BASE_DIR/'static'/'css'/'plugins'/'dropzone',
    BASE_DIR/'static'/'css'/'plugins'/'fullcalendar',
    BASE_DIR/'static'/'css'/'plugins'/'iCheck',
    BASE_DIR/'static'/'css'/'plugins'/'images',
    BASE_DIR/'static'/'css'/'plugins'/'images'/'bootstrap-colorpicker',
    BASE_DIR/'static'/'css'/'plugins'/'ionRangeSlider',
    BASE_DIR/'static'/'css'/'plugins'/'jasny',
    BASE_DIR/'static'/'css'/'plugins'/'jqGrid',
    BASE_DIR/'static'/'css'/'plugins'/'jQueryUI',
    BASE_DIR/'static'/'css'/'plugins'/'jQueryUI'/'images',
    BASE_DIR/'static'/'css'/'plugins'/'jsTree',
    BASE_DIR/'static'/'css'/'plugins'/'morris',
    BASE_DIR/'static'/'css'/'plugins'/'nouslider',
    BASE_DIR/'static'/'css'/'plugins'/'social-buttons',
    BASE_DIR/'static'/'css'/'plugins'/'steps',
    BASE_DIR/'static'/'css'/'plugins'/'summernote',
    BASE_DIR/'static'/'css'/'plugins'/'switchery',
    BASE_DIR/'static'/'css'/'plugins'/'toastr',

    BASE_DIR/'static'/'email_templates',
    BASE_DIR/'static'/'email_templates'/'img',

    BASE_DIR/'static'/'font-awesome'/'css',
    BASE_DIR/'static'/'font-awesome'/'fonts',
    BASE_DIR/'static'/'font-awesome'/'less',
    BASE_DIR/'static'/'font-awesome'/'scss',

    BASE_DIR/'static'/'fonts',
    BASE_DIR/'static'/'fonts'/'OpenSans',

    BASE_DIR/'static'/'img',
    BASE_DIR/'static'/'img'/'gallery',

    BASE_DIR/'static'/'js',
    # BASE_DIR/'static'/'js'/'bootstrap.js',
    BASE_DIR/'static'/'js'/'demo',
    BASE_DIR/'static'/'js'/'plugins',
    BASE_DIR/'static'/'js'/'plugins'/'blueimp',
    BASE_DIR/'static'/'js'/'plugins'/'chartJs',
    BASE_DIR/'static'/'js'/'plugins'/'chosen',
    BASE_DIR/'static'/'js'/'plugins'/'codemirror',
    BASE_DIR/'static'/'js'/'plugins'/'colorpicker',
    BASE_DIR/'static'/'js'/'plugins'/'cropper',
    BASE_DIR/'static'/'js'/'plugins'/'datapicker',
    BASE_DIR/'static'/'js'/'plugins'/'dataTables',
    BASE_DIR/'static'/'js'/'plugins'/'dropzone',
    BASE_DIR/'static'/'js'/'plugins'/'easypiechart',
    BASE_DIR/'static'/'js'/'plugins'/'flot',
    BASE_DIR/'static'/'js'/'plugins'/'fullcalendar',
    BASE_DIR/'static'/'js'/'plugins'/'gritter',
    BASE_DIR/'static'/'js'/'plugins'/'iCheck',
    BASE_DIR/'static'/'js'/'plugins'/'ionRangeSlider',
    BASE_DIR/'static'/'js'/'plugins'/'jasny',
    BASE_DIR/'static'/'js'/'plugins'/'jeditable',
    BASE_DIR/'static'/'js'/'plugins'/'jqGrid',
    BASE_DIR/'static'/'js'/'plugins'/'jQuery-ui',
    BASE_DIR/'static'/'js'/'plugins'/'jQuery-ui'/'i18n',
    BASE_DIR/'static'/'js'/'plugins'/'jQuery-ui'/'images',
    # BASE_DIR/'static'/'js'/'plugins'/'jsKonb',
    BASE_DIR/'static'/'js'/'plugins'/'jsTree',
    BASE_DIR/'static'/'js'/'plugins'/'justified-gallery',
    BASE_DIR/'static'/'js'/'plugins'/'metisMenu',
    BASE_DIR/'static'/'js'/'plugins'/'morris',
    BASE_DIR/'static'/'js'/'plugins'/'nestable',
    BASE_DIR/'static'/'js'/'plugins'/'nouslider',
    BASE_DIR/'static'/'js'/'plugins'/'pace',
    BASE_DIR/'static'/'js'/'plugins'/'peity',
    BASE_DIR/'static'/'js'/'plugins'/'rickshaw',
    BASE_DIR/'static'/'js'/'plugins'/'rickshaw'/'vendor',
    BASE_DIR/'static'/'js'/'plugins'/'slimscroll',
    BASE_DIR/'static'/'js'/'plugins'/'sparkline',
    BASE_DIR/'static'/'js'/'plugins'/'staps',
    BASE_DIR/'static'/'js'/'plugins'/'summernote',
    BASE_DIR/'static'/'js'/'plugins'/'switchery',
    BASE_DIR/'static'/'js'/'plugins'/'toastr',
    BASE_DIR/'static'/'js'/'plugins'/'validate',
    BASE_DIR/'static'/'js'/'plugins'/'video',
    ]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
