# Generated by Django 3.2 on 2025-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('Customer_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Alt_Phone_Number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('Customer_Type', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('Customer_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Date_of_Birth', models.DateField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
