# Generated by Django 5.1.5 on 2025-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='Model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='Vehicle_No',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
