# Generated by Django 5.1.5 on 2025-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customerdetails_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Alt_Phone_Number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Phone_Number',
            field=models.IntegerField(max_length=15),
        ),
    ]
