# Generated by Django 5.1.5 on 2025-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customerdetails_alt_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Alt_Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
