# Generated by Django 5.1.5 on 2025-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_phone_number_employeemaster_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeMaster',
        ),
    ]
