# Generated by Django 5.1.5 on 2025-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_employeemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('Employee_Name', models.CharField(max_length=50)),
                ('Employee_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Date_Of_Joining', models.DateField()),
            ],
        ),
    ]
