# Generated by Django 5.1.5 on 2025-01-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_employeemaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeMaster',
        ),
    ]
