# Generated by Django 5.1.5 on 2025-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_employeemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='Address',
            field=models.CharField(default='no address', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Vehicle_No',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
