# Generated by Django 5.1.5 on 2025-01-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_employeemaster_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='Address',
            new_name='Employee_Address',
        ),
    ]
