# Generated by Django 5.1.5 on 2025-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_employeemaster_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Id', models.CharField(max_length=50)),
                ('Material_Name', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Sub_Categories', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
            ],
        ),
    ]
