# Generated by Django 5.1.5 on 2025-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_materialmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmaster',
            name='Material_Make',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
