# Generated by Django 5.1.5 on 2025-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_materialmaster_material_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmaster',
            name='Material_Make',
            field=models.CharField(max_length=50),
        ),
    ]
