# Generated by Django 5.1.5 on 2025-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_employeemaster_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmaster',
            name='id',
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='Material_Id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
