# Generated by Django 5.1.5 on 2025-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_materialmaster_id_materialmaster_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Id', models.CharField(max_length=50)),
                ('Inward_ID', models.CharField(max_length=50)),
                ('Vendor_Name', models.CharField(max_length=50)),
                ('Vendor_Mobile', models.IntegerField()),
                ('Vendor_GST', models.CharField(max_length=50)),
                ('Cost_Per_Unit', models.CharField(max_length=50)),
                ('Selling_Cost', models.CharField(max_length=50)),
                ('Invoice_Cost', models.CharField(max_length=50)),
                ('Invoice_Quantity', models.IntegerField()),
                ('Serial_No', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InwardMaster',
            fields=[
                ('Material_Id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Inward_Id', models.CharField(max_length=50, unique=True)),
                ('Vendor_Name', models.CharField(max_length=50)),
                ('Vendor_Mobile', models.IntegerField()),
                ('Vendor_GST', models.CharField(max_length=50)),
                ('Cost_Per_Unit', models.CharField(max_length=50)),
                ('Selling_Cost', models.CharField(max_length=50)),
                ('Invoice_Cost', models.CharField(max_length=50)),
                ('Invoice_Quantity', models.IntegerField()),
            ],
        ),
    ]
