# Generated by Django 5.1.5 on 2025-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_inwarddetails_inwardmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwarddetails',
            old_name='Inward_ID',
            new_name='Inward_Id',
        ),
    ]
