# Generated by Django 5.1.5 on 2025-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_rename_inward_id_inwarddetails_inward_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarddetails',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inwardmaster',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
