# Generated by Django 5.1.5 on 2025-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_inwarddetails_status_inwardmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Vehicle_No',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
