# Generated by Django 5.1.5 on 2025-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_customerdetails_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
