# Generated by Django 5.1.5 on 2025-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_customerdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Alt_Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
