# Generated by Django 5.1.5 on 2025-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_customerdetails_alt_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inwarddetails',
            name='Vendor_Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Vendor_Mobile',
            field=models.BigIntegerField(),
        ),
    ]
