# Generated by Django 5.1.5 on 2025-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_customermaster_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardmaster',
            name='Inward_Id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Material_Id',
            field=models.CharField(max_length=50),
        ),
    ]
