# Generated by Django 5.1.5 on 2025-02-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_inwardmaster_material_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
        migrations.DeleteModel(
            name='CustomerMaster',
        ),
        migrations.DeleteModel(
            name='EmployeeMaster',
        ),
        migrations.DeleteModel(
            name='InwardDetails',
        ),
        migrations.DeleteModel(
            name='InwardMaster',
        ),
        migrations.DeleteModel(
            name='MaterialMaster',
        ),
    ]
