# Generated by Django 5.1.5 on 2025-02-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0031_delete_customerdetails_delete_customermaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('Customer_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Alt_Phone_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('Customer_Type', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Status', models.IntegerField(default=1)),
                ('Vehicle_No', models.CharField(max_length=55, unique=True)),
                ('Model', models.CharField(max_length=50)),
                ('Make', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('Customer_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Date_of_Birth', models.DateField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('Employee_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Date_Of_Joining', models.DateField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InwardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Id', models.CharField(max_length=50)),
                ('Inward_Id', models.CharField(max_length=50)),
                ('Vendor_Name', models.CharField(max_length=50)),
                ('Vendor_Mobile', models.BigIntegerField()),
                ('Vendor_GST', models.CharField(max_length=50)),
                ('Cost_Per_Unit', models.CharField(max_length=50)),
                ('Selling_Cost', models.CharField(max_length=50)),
                ('Invoice_Cost', models.CharField(max_length=50)),
                ('Invoice_Quantity', models.IntegerField()),
                ('Serial_No', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InwardMaster',
            fields=[
                ('Material_Id', models.CharField(max_length=55)),
                ('Inward_Id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Vendor_Name', models.CharField(max_length=50)),
                ('Vendor_Mobile', models.BigIntegerField()),
                ('Vendor_GST', models.CharField(max_length=50)),
                ('Cost_Per_Unit', models.CharField(max_length=50)),
                ('Selling_Cost', models.CharField(max_length=50)),
                ('Invoice_Cost', models.CharField(max_length=50)),
                ('Invoice_Quantity', models.IntegerField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('Material_Id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Material_Name', models.CharField(max_length=50)),
                ('Material_Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Sub_Categories', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
