# Generated by Django 5.1.5 on 2025-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarddetails',
            name='Batch_Id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inwardmaster',
            name='Batch_Id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
